// Bundles the Compensation Planner's browser code (main.js and what it imports, including
// compensation-projection.js and compensation-calc.js) into one script, written as a string
// module the Worker serves at /compensation-planner/app.js. Run after changing any file it uses:
//   node apps/finance/planner/build.mjs
// test/finance-compensation-planner-native.test.js fails when the committed bundle is stale.
import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
export const BUNDLE_PATH = here('./bundle.generated.js');

export async function bundlePlanner() {
  const result = await build({
    entryPoints: [here('./main.js')],
    bundle: true, format: 'iife', target: 'es2020', write: false, legalComments: 'none',
    charset: 'utf8', minify: true,
  });
  return result.outputFiles[0].text;
}

export function bundleModule(js) {
  return '// Generated by apps/finance/planner/build.mjs from apps/finance/planner/*.js. Do not edit.\n'
    + 'export const PLANNER_APP_JS = ' + JSON.stringify(js) + ';\n';
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const js = await bundlePlanner();
  writeFileSync(BUNDLE_PATH, bundleModule(js));
  console.log(`Wrote ${BUNDLE_PATH} (${(js.length / 1024).toFixed(1)} KB)`);
}
