// Bundles the Tuition Aid planner's browser code (main.js and what it imports) into one script,
// written as a string module the Worker serves at /tuition-planner/app.js. Run after changing any
// file it uses:
//   node apps/finance/tuition-planner/build.mjs
// test/finance-tuition-planner.test.js fails when the committed bundle is stale.
import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
export const BUNDLE_PATH = here('./bundle.generated.js');

export async function bundleTuitionPlanner() {
  const result = await build({
    entryPoints: [here('./main.js')],
    bundle: true, format: 'iife', target: 'es2020', write: false, legalComments: 'none',
    charset: 'utf8', minify: true,
  });
  return result.outputFiles[0].text;
}

export function bundleModule(js) {
  return '// Generated by apps/finance/tuition-planner/build.mjs from apps/finance/tuition-planner/*.js. Do not edit.\n'
    + 'export const TUITION_PLANNER_JS = ' + JSON.stringify(js) + ';\n';
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const js = await bundleTuitionPlanner();
  writeFileSync(BUNDLE_PATH, bundleModule(js));
  console.log(`Wrote ${BUNDLE_PATH} (${(js.length / 1024).toFixed(1)} KB)`);
}
